keys:
  - &freeman 6CC1 D9A2 3BEF F841 D1B2  512B 5AF7 AFBF 695E 8A5D
  - &office age1uslkhdyuqxn24rhe77v2acfx4tzn6ywyhgqqkalnqxm0y3mkk9rqqsngvf
  - &mail age14z507h9qugzy65rpfgrzlrzkvyvwsqlwv7nguamaw4wx830hsu0qt23vx3
  - &digital age1d9znzzt6zkk4c9tnrqpwl52pdh7u8qte33k244d65rajwku3lulsm2l85p

creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *office
          - *mail
          - *digital
        pgp:
          - *freeman
